### ISSUE TITLE
Great tutorial, i follow all the step to install Cuda 11.8 but i when i run nvcc -V, i get Cuda 11.5. I have not install Cuda 11.5 before.

### ISSUE THREAD

**Issue by namogg** [FahimFBA/CUDA-WSL2-Ubuntu#3]
**Problem statement**:
Great tutorial, i follow all the step to install Cuda 11.8 but i when i run nvcc -V, i get Cuda 11.5. I have not install Cuda 11.5 before.

**Stats**:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

**Comment by FahimFBA** [comment]
Can you please check whether you have multiple versions of CUDA installed already in your system or not?

**Comment by namogg** [comment]
i solved it by install Cuda 12.2, thanks for your tutorial.

**Comment by FahimFBA** [comment]
> i solved it by install Cuda 12.2, thanks for your tutorial.

Thank you so much for your kind words. I am glad that you solved the issue. 😊
