### ISSUE TITLE
How to install cudnn?

### ISSUE THREAD

**Issue by Acgholic** [FahimFBA/CUDA-WSL2-Ubuntu#4]
A good guideline. But how to install cudnn after installing cuda?

**Comment by FahimFBA** [comment]
Simply install the Linux-Ubuntu one:

[https://developer.nvidia.com/cudnn-downloads?target_os=Linux](https://developer.nvidia.com/cudnn-downloads?target_os=Linux)

**Comment by Acgholic** [comment]
Is the way to install cudnn suitable for wsl-ubuntu?

**Comment by FahimFBA** [comment]
> Is the way to install cudnn suitable for wsl-ubuntu?

Yes. 

I was also working on V2 of this project where I would have shown them in detail. But that hasn't started yet as I am not getting time for that.

**Comment by Acgholic** [comment]
> > Is the way to install cudnn suitable for wsl-ubuntu?
> 
> Yes.
> 
> I was also working on V2 of this project where I would have shown them in detail. But that hasn't started yet as I am not getting time for that.

Thank you. I will try it.
